# Generated by Django 6.0 on 2025-12-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automotive_app', '0002_sparepart_booking_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentingrequest',
            name='estimated_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
