# Generated by Django 6.0 on 2025-12-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automotive_app', '0003_dentingrequest_estimated_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
