# Generated by Django 6.0 on 2026-01-01 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Automotive_app', '0005_partorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartOrder',
        ),
    ]
