# Generated by Django 6.0 on 2026-01-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automotive_app', '0013_alter_partorder_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='final_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='partorder',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'RefundED')], default='PENDING', max_length=20),
        ),
    ]
