# Generated by Django 6.0 on 2026-01-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automotive_app', '0016_alter_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentingrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='denting_estimates/'),
        ),
    ]
