# Generated by Django 6.0 on 2026-01-23 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Automotive_app', '0017_dentingrequest_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentingrequest',
            name='image',
        ),
    ]
