# Generated by Django 6.0 on 2026-01-28 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automotive_app', '0018_remove_dentingrequest_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicehistory',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='Automotive_app.booking'),
        ),
    ]
