# Generated by Django 6.0 on 2026-01-28 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automotive_app', '0019_servicehistory_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicehistory',
            name='booking',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='Automotive_app.booking'),
            preserve_default=False,
        ),
    ]
