# Generated by Django 6.0 on 2026-01-28 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Automotive_app', '0020_alter_servicehistory_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicehistory',
            name='booking',
        ),
    ]
