# Generated by Django 6.0 on 2026-02-16 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automotive_app', '0022_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sparepart',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='sparepart',
            name='is_available',
        ),
        migrations.AddField(
            model_name='sparepart',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Current quantity in inventory', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
