# Generated by Django 6.0 on 2026-02-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automotive_app', '0023_alter_sparepart_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partorder',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
